### PR TITLE
Bugfix 04-04-21 Symbol Encoding

### LINKED ISSUE #518: Axes Labels not displaying correctly
**Describe the bug**
Some of the symbols used in the axes labels are not displaying correctly, such as Angstrom, Delta etc - this visual issue is consistent across multiple modules within the dissolve-gui. I have attached a couple of screenshots showing the issue. The issue was seen on the last 0.7.0 build and the new 0.8.0 build too.

**Screenshots**
AxesLabelIssue
AxesLabelIssue2

**Operating System:**
 - OS:  Windows 10

### PR DESCRIPTION
**Pull request by trisyoungs**
This PR attempts to fix #518, moving the storage of UTF-8 escaped chars from `std::string` to `QString`. This is valid since the relevant code is GUI-specific, and the use of `std::wstring` creates friction with `std::string` uses already in place.

Closes #518.

### CODE REVIEW

**Comment by trisyoungs** [comment]
@calum-green - this is an attempt to fix the missing symbols bug you observed on Windows. If you have a free minute, could you try out the Windows installer for this version (https://dev.azure.com/DisorderedMaterials/Dissolve/_build/results?buildId=1688&view=artifacts&pathAsName=false&type=publishedArtifacts) and see if it fixes it?

**Comment by calum-green** [comment]
I have downloaded the windows build from the link, however, I am unable to load any old input files in properly (a separate issue? - related to reference data). I can view the graphs in the modules where they weren't displaying previously (although with no data due to issue) and the axis labels do not seem to be fixed.

image
image

**Comment by trisyoungs** [comment]
OK, attempt number two now at https://dev.azure.com/DisorderedMaterials/Dissolve/_build/results?buildId=1716&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by calum-green** [comment]
This one works better - but there are still a couple of little things. The units of Q (inverse angstrom) do not have any real difference visually from normal angstrom, seen as units of r. The superscript '-1' is not very clear if it is there or not, on another axis label it is clear to see in 'kJ mol^-1'.

image
image

The capital delta symbol seems to be the only one not present still and renders a question mark - it's within the Refine (EPSR)...EPSR...Output...Delta F(Q) module.

image

Also, units of EReq (kJ mol^-1) have disappeared - I wanted to check this was supposed to happen?

**Comment by trisyoungs** [comment]
OK, some work to be done here.  I'll stop guessing and try a proper Windows-based investigation next week.

**Pull request closed without merging**
