### PR TITLE
Windows Test Fix

### PR DESCRIPTION
**Pull request by trisyoungs**
Fixup test suite for Windows.

### CODE REVIEW

**Review by Danbr4d — COMMENTED** [review]
A few failed tests and a something with QT6 not working, but the tests are running locally now.
image

**Comment by trisyoungs** [comment]
To be honest I took a chance and assumed this PR was finished / working, but I hadn't run the Qt-based tests because of the library moving / deployment stuff.  I'll do that when I can, but it may not be until mid / late afternoon.

**Comment by trisyoungs** [comment]
@Danbr4d This PR is ready for your approval - the other failing tests on Windows are accounted for as per our other conversation.

**Review by Danbr4d — APPROVED** [review]
This all works now the only failures are the ones you previously mentioned

**Pull request merged**
