### PR TITLE
Include std::any in CIFImportParser

### LINKED ISSUE #1032: CI is broken by Homebrew upgrade to Antlr 1.40
Homebrew recently upgraded to Antlr 4.10 and there is no mechanism for installing the older version.  This means that we must make our code compatible with 4.10.

### PR DESCRIPTION
**Pull request by rprospero**
Fix the grammars to support ANTLR 4.10.  This will close #1032.

### CODE REVIEW

**Comment by trisyoungs** [comment]
Maybe I'm missing something, but what why are we using the Homebrew ANTLR4 as opposed to that from conan? We can download any Java binary version from the ANTLR4 website if that's the issue.

**Comment by rprospero** [comment]
I'm an idiot.  I already moved the antlr runtime into conan as part of cleaning up the Windows development environment.  So downloading the Antlr jar file that matches the runtime version is the only possible solution.

**Comment by trisyoungs** [comment]
Heh - well let's hope this is enough to satisfy OSX. Easily the winner for the most awkward cross-platform target award.

**Comment by trisyoungs** [comment]
Also, don't forget that we already have an `ANTLR_EXECUTABLE` option defined in our CMake.

**Pull request merged**
