### PR TITLE
1306 clear module data

### LINKED ISSUE #1306: Clear all module data from specific layer
**Describe the feature / issue**
Add an option to the layer tab context menu (or somewhere else appropriate) to allow clearing of module data for all the modules within that layer.  Useful for occasions when a layer further down the chain remained activated by mistake while equilibrating / preparing a system, for instance.

### PR DESCRIPTION
**Pull request by Danbr4d**
Closes #1306. Adds in function to clear all module data from a layer

### CODE REVIEW

**Comment by Danbr4d** [comment]
I tried only changing setup() back but that gave the same error until I also changed reconcile() back. 
When using clearmoduledata() at the moment there is a crash as well

**Review by trisyoungs — APPROVED** [review]
:+1:

**Comment by trisyoungs** [comment]
This works just fine, but after actually using it I think we should have a confirmation dialog to make sure that's what the user wants to do.  Should also have one in the original module-specific "Clear module data" option as well, in hindsight.

You can more-or-less copy the code from `src/gui/menu_simulation.cpp` starting on line 62 and change the message.

**Review by trisyoungs — APPROVED** [review]
:+1:

**Pull request merged**
